update-checker:
  interval: 2 # hours
  enabled: true

# Debug: true enables the following
# Games starting 20 seconds after startup
# Time between games becomes 1 minute
# Send op's the answer to all questions
# Removes minimum players needed
# Disables rewards
debug: false

storage:
  #Valid storage types:
  # - json
  # - sqlite
  # - mysql
  type: "json"
  mysql:
    db-name: simplechatgames
    ip: 127.0.0.1
    port: '3306'
    username: simplechatgames
    password: simplechatgames

games:
  interval: 5 # Minutes
  players: 2
  not-enough-players-message: "<green>Not enough players online"
  # Valid sounds can be found on the following link
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sounds:
    enabled: false
    start: BLOCK_ANVIL_LAND
    win: ENTITY_VILLAGER_YES


rewards:
  item:
    enabled: false
    value: empty
  economy:
    enabled: false
    value: 0
  command:
    enabled: false
    value: 0