name: SimpleChatGames
version: '${version}'
main: me.epic.chatgames.SimpleChatGames
api-version: 1.17
softdepend: [Vault, PlaceholderAPI]
libraries:
  - 'com.zaxxer:HikariCP:5.0.1'
  - 'net.kyori:adventure-platform-bukkit:4.2.0'
  - 'net.kyori:adventure-api:4.13.0'
  - 'net.kyori:adventure-text-minimessage:4.13.0'


commands:
  simplechatgames:
    aliases:
      - cg
      - scg
      - chatgames
