name: SimpleChatGames
version: '${version}'
main: me.epic.chatgames.SimpleChatGames
api-version: 1.17
softdepend: [Vault, PlaceholderAPI]

commands:
  simplechatgames:
    aliases:
      - cg
      - scg
      - chatgames
